### ISSUE TITLE
Refactor auth layer from JWT to OAuth 2.0

### ISSUE THREAD

**Issue by Alex-D** [Colllect/Colllect#67]
https://symfony.com/doc/current/security/guard_authentication.html

**Comment by lostdesign** [comment]
Hey Alex, may I ask you what made you decide to use OAuth2.0 for the authentication for the SPA over the JWT?

**Comment by Alex-D** [comment]
Finally, I use both OAuth 2.0 *and* JWT :D

**Comment by lostdesign** [comment]
Oh that is internally JWT and external auth being OAuth or how come?

**Comment by Alex-D** [comment]
I use this bundle if you want to check:
https://github.com/trikoder/oauth2-bundle

itself based on:
https://oauth2.thephpleague.com/

which implements both OAuth2 and JWT at the same time.

**Comment by lostdesign** [comment]
Thanks, the same exists in laravel which is "passport" - gonna use that in the next project.

Was just wondering why you replaced it which it seems you did not 😅
