### ISSUE TITLE
"make reset" removes *all* docker images

### ISSUE THREAD

**Issue by iwconfig** [Colllect/Colllect#99]
Hello again, one more friendly FYI.

I ran `make down` followed by `make reset` and it removed every single one of my docker images, not just the ones related to `Collect`.

I know this is still under heavy development but _with much leniency_ let me just tell you: **This is kind of annoying! to say the least.**

I should've inspected `Makefile` more than I did. :upside_down_face:

**Comment by Alex-D** [comment]
Yeah, I know, but sometimes I need to clean everything. If you have tips to filter images, I will be more than happy to apply them, but since images can be untagged, it's not easy to make a clean reset.

I have to admit that it's not very well documented
Sorry for the full reset ^^'
